//TT VARIABLES DE ENTORNO
export const ENV = {
  //GENERAL
  PORT: process.env.PORT || 3000,
  TZ: process.env.TZ,
  NODE_ENV: process.env.NODE_ENV || 'development',
  //IDIOMA
  LOCALE: process.env.LOCALE || 'es',
  //usuario
  USER_ID: process.env.USER_ID,
  //servicio2
  SERVICE_URL: process.env.SERVICE_URL || 'http://localhost:3000',
  SERVICE_ID: process.env.SERVICE_ID,
  SERVICE_TOKEN: process.env.SERVICE_TOKEN,

  //TOKENS JWT
  JWT_BAILEYS_CONNECT: process.env.JWT_BAILEYS_CONNECT || 'jwt-access-token-baileys-connect',

  //AGENTE - PROVEEDOR DE IA
  //openAI
  AI_PROVIDER: process.env.AI_PROVIDER,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,

  //PLATAFORMAS
  //WHATSAPP
  PROV_WHATSAPP: process.env.PROV_WHATSAPP,
  WHATSAPP_META_PHONEID: process.env.WHATSAPP_META_PHONEID,
  WHATSAPP_META_ACCOUNTID: process.env.WHATSAPP_META_ACCOUNTID,
  WHATSAPP_META_TOKEN: process.env.WHATSAPP_META_TOKEN,
  WHATSAPP_META_VERSION: process.env.WHATSAPP_META_VERSION,

  //FACEBOOK MESSENGER
  FACEBOOK_MESSENGER_PAGEID: process.env.FACEBOOK_MESSENGER_PAGEID,
  FACEBOOK_MESSENGER_TOKEN: process.env.FACEBOOK_MESSENGER_TOKEN,
  FACEBOOK_VERSION: process.env.FACEBOOK_VERSION,

  //INSTAGRAM MESSENGER
  INSTAGRAM_MESSENGER_PAGEID: process.env.INSTAGRAM_MESSENGER_PAGEID,
  INSTAGRAM_MESSENGER_TOKEN: process.env.INSTAGRAM_MESSENGER_TOKEN,
  INSTAGRAM_VERSION: process.env.INSTAGRAM_VERSION,

  //STORAGE
  STORAGE: process.env.STORAGE,
  //IMAGE KIT
  IMAGEKIT_ID: process.env.IMAGEKIT_ID,
  IMAGEKIT_PRIVATE_KEY: process.env.IMAGEKIT_PRIVATE_KEY,
  IMAGEKIT_PUBLIC_KEY: process.env.IMAGEKIT_PUBLIC_KEY,

  //FRONTEND
  //APPSHEET
  APP_FRONTEND: process.env.APP_FRONTEND,
  APPSHEET_ID: process.env.APPSHEET_ID,
  APPSHEET_TOKEN: process.env.APPSHEET_TOKEN,
  APPSHEET_ECO: process.env.APPSHEET_ECO,
  APPSHEET_INBOX: process.env.APPSHEET_INBOX,

  //BANDEJAS
  //CHATWOOT
  CHATWOOT_URL: process.env.CHATWOOT_URL,
  CHATWOOT_COUNT_ID: process.env.CHATWOOT_COUNT_ID,
  CHATWOOT_AGENT_ID: process.env.CHATWOOT_AGENT_ID,
  CHATWOOT_TOKEN: process.env.CHATWOOT_TOKEN,
  CHATWOOT_ECO: process.env.CHATWOOT_ECO,
  //Whatsapp inbox
  CHATWOOT_WHATSAPP_ID: process.env.CHATWOOT_WHATSAPP_ID,
  CHATWOOT_WHATSAPP_TOKEN: process.env.CHATWOOT_WHATSAPP_TOKEN,
  //Messenger inbox
  CHATWOOT_MESSENGER_ID: process.env.CHATWOOT_MESSENGER_ID,
  CHATWOOT_MESSENGER_TOKEN: process.env.CHATWOOT_MESSENGER_TOKEN,
  //Instagram inbox
  CHATWOOT_INSTAGRAM_ID: process.env.CHATWOOT_INSTAGRAM_ID,
  CHATWOOT_INSTAGRAM_TOKEN: process.env.CHATWOOT_INSTAGRAM_TOKEN,

  //SMTP EMAIL
  SMTP_EMAIL: process.env.SMTP_EMAIL,
  SMTP_SERVICE: process.env.SMTP_SERVICE,
  SMTP_PORT: process.env.SMTP_PORT,
  SMTP_TOKEN: process.env.SMTP_TOKEN,

  //FACTURAPP
  FACTURAPP_USER: process.env.FACTURAPP_USER,
  FACTURAPP_APIKEY: process.env.FACTURAPP_APIKEY,
  FACTURAPP_URL: process.env.FACTURAPP_URL,

  //CONFIG
  FACTURAPP_ACTIVE: process.env.FACTURAPP_ACTIVE === 'true',
}

//TT ESTADO DE ENTORNO
export function isProductionEnv() {
  return ENV.NODE_ENV === 'production'
}
